INSERT INTO Producto VALUES('camisa manga larga','Roja', 10)
INSERT INTO Producto VALUES('camisa manga corta','Azul', 9)
INSERT INTO Producto VALUES('corset','Rojo', 25)
INSERT INTO Producto VALUES('tanga','Negra', 3)
INSERT INTO Producto VALUES('falda','Azul', 13)
INSERT INTO Producto VALUES('medias malla','Verde', 5)
INSERT INTO Producto VALUES('vestido floreado','Floreado', 15)
INSERT INTO Producto VALUES('pantalon','negro', 23)
INSERT INTO Producto VALUES('cinturilla de cuero','Negra', 35)
INSERT INTO Producto VALUES('licra','Violeta', 6)